# Generated by Django 4.2 on 2023-12-05 16:39

from django.db import migrations, models
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_profile_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='debate_title',
            field=models.TextField(validators=[logic.models.validate_word_length]),
        ),
    ]
