# Generated by Django 4.2 on 2023-12-05 16:47

from django.db import migrations, models
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_alter_poll_debate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(validators=[logic.models.validate_word_length]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[logic.models.validate_word_length]),
        ),
    ]
