# Generated by Django 4.2 on 2023-12-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/profiles/picTest.jpg', null=True, upload_to='profiles/'),
        ),
    ]
